import Head from 'next/head';
import Nav from '../components/nav';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Nav />
                <div className="bg-color1"></div>
                <h1>This is the HomePage</h1>
            </main>

            <footer></footer>
        </div>
    );
}
